1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that they are two procedure yields to same result
* What percent of the total variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import linalg as la

In [23]:
N=5000
x1= np.random.normal(0,1,N)
x2= x1 + np.random.normal(0,3,N)
x3= 2*x1 + x2

dataset=np.array([x1,x2,x3])
#print(dataset)
cov=np.cov(dataset)
print("Covariance matrix: \n", cov)

#Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
l, V = np.linalg.eig(cov) 
print("Eigenvalues: \n", l)
print("Eigenvectors: \n", V)

#Find the eigenvectors and eigenvalues using SVD
U, spectrum, Vt = la.svd(dataset)

print("shapes:", U.shape,  spectrum.shape, Vt.shape)

l_svd = spectrum**2/(N-1)
V_svd = U
print("Eigenvalues SVD: \n", l_svd)
print("Eigenvectors SVD: \n", V_svd)

#Reduce the dimensionality of the system so that at least 99% of the total variability is retained
#The third eigenvalue is almost 0. This is reasonable, in fact the variable x3 is a linear combination of x1 and x2
r=(l_svd[0]+l_svd[1])/np.sum(l_svd)
print(r)

#Redefine the data in the basis yielded by the PCA procedure

Covariance matrix: 
 [[ 1.01327483  0.96026611  2.98681578]
 [ 0.96026611  9.98151748 11.9020497 ]
 [ 2.98681578 11.9020497  17.87568125]]
Eigenvalues: 
 [ 2.68136294e+01 -5.24352671e-16  2.05684414e+00]
Eigenvectors: 
 [[-0.11504418 -0.81649658  0.56577219]
 [-0.5778824  -0.40824829 -0.70667196]
 [-0.80797077  0.40824829  0.42487241]]
shapes: (3, 3) (3,) (5000, 5000)
Eigenvalues SVD: 
 [2.68222822e+01 2.05684462e+00 9.05685300e-32]
Eigenvectors SVD: 
 [[-0.11504272  0.56577249 -0.81649658]
 [-0.57788423 -0.70667047 -0.40824829]
 [-0.80796967  0.4248745   0.40824829]]
1.0


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset